
import os, sqlite3

# This file is created in the current directory.
con = sqlite3.connect('database/database.db')

# Create all tables.
con.execute('CREATE TABLE object (id INTEGER PRIMARY KEY, name TEXT NOT NULL, descr TEXT, cat TEXT, lbl TEXT, date TEXT, price INTEGER)')
con.execute('CREATE TABLE categories (id TEXT PRIMARY KEY, name TEXT NOT NULL)')
con.execute('CREATE TABLE labels (id INTEGER PRIMARY KEY, name TEXT NOT NULL)')
con.execute('CREATE TABLE logs (id INTEGER PRIMARY KEY, operation TEXT NOT NULL)')

# Populate with a few Objects.
con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES (1001,'Set cercei + bratara cipsuri jad verde','...','BC','cips, verde','2010-10-03',22)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + bratara hematit sferic','...','BC','hematit, negru','2010-10-03',22)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + bratara perle argintii','...','BC','argintiu','2010-10-03',26)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei ceramica perla + lacrima','Diferite culori: rosu/ portocaliu/ albastru/ violet/ negru.','C2','ceramica, rosu, portocaliu, albastru, violet, negru','2010-10-03',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei ovali ceramica','Diferite culori: galben/ portocaliu/ rosu','C2','ceramica, galben, portocaliu, rosu','2010-10-03',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei ciorchine','Diferite culori: rosii/ violet/ roz.','C2','rosu, violet, roz','2010-10-03',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cipsuri lapis lazuli','...','C2','cips, lapis lazuli, albastru','2010-10-15',5)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cipsuri lapis lazuli lungi','...','C2','cips, lapis lazuli, albastru','2010-10-15',9)")

con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES ('1009','Set cercei + bratara cipsuri coral rosu','...','BC','cips, coral, rosu','2010-10-15',24)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei melc + perle','Diferite culori: rosu/ albastru/ negru','C2','melc, rosu, albastru, negru','2010-10-15',9)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei melc simplu','...','C2','melc','2010-10-15',6)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei 3 cipsuri coral portocaliu','...','C2','cips, coral, portocaliu','2010-10-15',5)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei 5 cipsuri coral portocaliu','...','C2','cips, coral, portocaliu','2010-10-15',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei 7 cristale swarovski','Diferite culori: ortocaliu, violet, roz, verde','C2','swarovski, portocaliu, violet, roz','2010-10-15',8)")

con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES ('1015','Cercei rotunzi cu 5 perle','Diferite culori: rosii/ roz/ violet','C2','rosu, roz, violet','2010-10-31',5)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei rotunzi cu cipsuri din coral rosu','...','C2','cips, coral, rosu','2010-10-31',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei ovali din sticla pictata','Diferite culori: verde/ albastru','C2','sticla, verde, albastru','2010-10-31',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei rotunzi','Diferite culori: verzi/ violet','C2','plastic, verde, violet','2010-10-31',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei lungi cu 5 cristale swarovski','...','C2','swarovski, verde','2010-11-07',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei melc + cristale albastre','...','C2','melc, albastru','2010-10-31',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei lacrima rosii inconjurati cu sarma','...','C2','rosii','2010-10-31',10)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu fluturas','Diferite culori: verzi/ violet.','C2','verde, violet','2010-10-31',7)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 2 perle roz','...','C2','roz','2010-10-31',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 2 lacrimi argintii','...','C2','argintiu','2010-10-31',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Bratara cu 3 melcisori si 3 perle','Diferite culori: rosu, albastru, negru.','B','melc, rosu, albastru, negru','2010-10-31',20)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei `lebada`','Diferite culori: rosu, albastru, negru.','C2','melc, rosu, albastru, negru','2010-10-31',8)")

con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES ('1027','Cercei sticla pictata rosie','...','C2','sticla, rosu','2010-11-07',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei jad rosu','...','C2','jad, rosu','2010-11-07',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 2 cristale fatetate albe','...','C2','sticla, alb','2010-11-07',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 3 perle','Culoare albastru, roz.','C2','albastru, roz','2010-11-07',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 2 cristale biconice','Cristale biconice albastru inchis.','C2','albastru','2010-11-07',8)")

con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES ('1032','Cercei `lebada`','Diferite culori: rosu, albastru, negru.','C2','melc, rosu, albastru, negru','2010-11-14',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu lant si perla','Perla si lantisor culoare neagra.','C2','lant, negru','2010-11-14',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu lant si cipsuri','Cipsuri din lapis lazuli, jad, etc.','C2','lant, cipsuri, lapis lazuli','2010-11-14',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Colier cu cipsuri coral rosu','Cipsuri coral rosu.','C0','cipsuri, coral, rosu','2010-11-14',15)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + colier cu cipsuri coral rosu','Cipsuri coral rosu.','CC','cipsuri, coral, rosu','2010-11-14',25)")

con.execute("INSERT INTO object (id,name,descr,cat,lbl,date,price) VALUES ('1037','Set cercei + colier flori','Floricelele sunt din plastic transparent si albastru deschis.','CC','plastic, alb, albastru','2010-11-14',20)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + colier cristale swarovski','...','CC','swarovski, roz, violet','2010-11-27',20)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + bratara perle violet stralucitor','...','BC','violet','2010-11-27',20)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu perle violet stralucitor','...','C2','violet','2010-11-27',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Set cercei + bratara piatra soarelui','...','BC','galben, auriu, maron','2010-11-27',20)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei piatra soarelui','...','C2','galben, auriu, maron','2010-11-27',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Bratara piatra soarelui','...','B','galben, auriu, maron','2010-11-27',10)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei globulete rosii','...','C2','rosu','2010-11-27',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 4 `bomboane` lila','...','C2','lila','2010-11-27',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei lacrima cu un cristal','Diferite culori: albastru, violet','C2','sticla, albastru, violet','2010-11-27',8)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei `Chandelier` cu cristale rosii','...','C2','rosu','2010-11-27',10)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei `ingeras`','Diferite culori: rosu, albastru','C2','rosu, albastru','2010-11-27',10)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Brosa cu globulete','Diferite culori: rosu, cenusiu','BO','rosu, cenusiu','2010-11-27',10)")
con.execute("INSERT INTO object (name,descr,cat,lbl,date,price) VALUES ('Cercei cu 5 cristale fatetate rosii','...','C2','rosu','2010-11-27',8)")

# A few categories.
con.execute("INSERT INTO categories (id,name) VALUES ('C0','Colier')")
con.execute("INSERT INTO categories (id,name) VALUES ('C2','Cercei')")
con.execute("INSERT INTO categories (id,name) VALUES ('B','Bratara')")
con.execute("INSERT INTO categories (id,name) VALUES ('P','Pandantiv')")
con.execute("INSERT INTO categories (id,name) VALUES ('I','Inel')")
con.execute("INSERT INTO categories (id,name) VALUES ('BO','Brosa')")
con.execute("INSERT INTO categories (id,name) VALUES ('BC','Bratara+Cercei')")
con.execute("INSERT INTO categories (id,name) VALUES ('CC','Colier+Cercei')")

# A few labels.
con.execute("INSERT INTO labels (id,name) VALUES (10,'negru')")
con.execute("INSERT INTO labels (name) VALUES ('alb')")
con.execute("INSERT INTO labels (name) VALUES ('cenusiu')")
con.execute("INSERT INTO labels (name) VALUES ('argintiu')")
con.execute("INSERT INTO labels (name) VALUES ('rosu')")
con.execute("INSERT INTO labels (name) VALUES ('roz')")
con.execute("INSERT INTO labels (name) VALUES ('lila')")
con.execute("INSERT INTO labels (name) VALUES ('galben')")
con.execute("INSERT INTO labels (name) VALUES ('auriu')")
con.execute("INSERT INTO labels (name) VALUES ('albastru')")
con.execute("INSERT INTO labels (name) VALUES ('portocaliu')")
con.execute("INSERT INTO labels (name) VALUES ('violet')")
con.execute("INSERT INTO labels (name) VALUES ('verde')")
con.execute("INSERT INTO labels (name) VALUES ('maron')")
con.execute("INSERT INTO labels (name) VALUES ('sarma')")
con.execute("INSERT INTO labels (name) VALUES ('lant')")
con.execute("INSERT INTO labels (name) VALUES ('argint')")
con.execute("INSERT INTO labels (name) VALUES ('plastic')")
con.execute("INSERT INTO labels (name) VALUES ('lemn')")
con.execute("INSERT INTO labels (name) VALUES ('sticla')")
con.execute("INSERT INTO labels (name) VALUES ('ceramica')")
con.execute("INSERT INTO labels (name) VALUES ('swarovski')")
con.execute("INSERT INTO labels (name) VALUES ('cips')")
con.execute("INSERT INTO labels (name) VALUES ('jad')")
con.execute("INSERT INTO labels (name) VALUES ('coral')")
con.execute("INSERT INTO labels (name) VALUES ('hematit')")
con.execute("INSERT INTO labels (name) VALUES ('lapis lazuli')")
con.execute("INSERT INTO labels (name) VALUES ('piatra soarelui')")
con.execute("INSERT INTO labels (name) VALUES ('melc')")

con.commit()

print('Done!')
os.system('pause')
